# ==========================================
# Raspberry Pi 3 publisher Dockerfile
# ==========================================

# Import base(line) image
#
#FROM pvln/mqtt-baseline:latest
#
# use lcoal file
# 
FROM mqtt-baseline:latest

LABEL version="0.1" \
      maintainer="Pierre Veelen <pierre@pvln.nl>"

# ==========================================
# START OF INSTALLING UTILITIES AND DEFAULTS
# ==========================================
RUN apt-get clean && \
    apt-get update && \
    sudo apt-get upgrade -y 

# ==========================================
# INSTALLING AND CONFIGURING UTILITIES
# ==========================================
# install curl and cleanup
RUN sudo apt-get install -y \
    curl && \
    sudo apt-get -y autoremove && \
    sudo apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install mosquitto client and cleanup
RUN sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa && \
    sudo apt-get update && \
    sudo apt-get -y install mosquitto-clients && \
    sudo apt-get -y autoremove && \
    sudo apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install jq and cleanup
RUN sudo apt-get update && \
    sudo apt-get -y install jq && \
    sudo apt-get -y autoremove && \
    sudo apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# ==========================================
# END OF UTILITIES AND DEFAULTS
# ==========================================

# ==========================================
# ENTRYPOINT & CMD
# ==========================================
#
# Inspiration: http://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
#
# Prefer ENTRYPOINT to CMD when building executable Docker image and you need a command always to be executed. 
# Additionally use CMD if you need to provide extra default arguments that could be overwritten from command line when docker container runs.
# Choose CMD if you need to provide a default command and/or arguments that can be overwritten from command line when docker container runs.
#

# Cancel any pre-defined start-up instruction and allow us to use our own.
#
ENTRYPOINT []

# Add our own entrypoint script.
#
ADD ./publisher.sh /usr/local/bin/
ENTRYPOINT ["/bin/bash","publisher.sh"]

# Don't need any specific arguments to be fed into entrypoint 
CMD []
